"""create_initial_pillsync_schema

Revision ID: 31956e6dd748
Revises: 
Create Date: 2026-08-30 12:15:56.357248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31956e6dd748'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('standard_strength', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_generic_name'), 'medicines', ['generic_name'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('PATIENT', 'CAREGIVER', 'ADMIN')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('caregiver_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY') OR gender IS NULL", name='ck_patient_gender'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('caregiver_patient_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('permission_level', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("permission_level IN ('VIEW_ONLY', 'FULL_ACCESS', 'ALERTS_ONLY')", name='ck_caregiver_permission'),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregiver_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caregiver_id', 'patient_id', name='uq_caregiver_patient')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_name', sa.String(length=150), nullable=True),
    sa.Column('clinic_hospital_name', sa.String(length=200), nullable=True),
    sa.Column('prescribed_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expiry_date IS NULL OR expiry_date >= prescribed_date', name='ck_prescription_dates'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'VERIFIED')", name='ck_ocr_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('prescription_id', sa.UUID(), nullable=True),
    sa.Column('custom_medicine_name', sa.String(length=200), nullable=True),
    sa.Column('dosage_amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('dosage_unit', sa.String(length=30), nullable=False),
    sa.Column('instructions', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dosage_amount > 0', name='ck_patient_med_dosage_amount'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_patient_med_dates'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patient_medications_patient_active', 'patient_medications', ['patient_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_patient_medications_patient_id'), 'patient_medications', ['patient_id'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_medication_id', sa.UUID(), nullable=False),
    sa.Column('frequency_type', sa.String(length=30), nullable=False),
    sa.Column('time_of_day_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.INTEGER()), nullable=True),
    sa.Column('dose_quantity', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency_type IN ('DAILY', 'SPECIFIC_DAYS', 'INTERVAL_DAYS', 'AS_NEEDED')", name='ck_schedule_frequency_type'),
    sa.CheckConstraint("time_of_day_type IN ('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', 'CUSTOM')", name='ck_schedule_time_of_day'),
    sa.CheckConstraint('dose_quantity > 0', name='ck_schedule_dose_quantity'),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medication_schedules_med_active', 'medication_schedules', ['patient_medication_id', 'is_active'], unique=False)
    op.create_table('medicine_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_medication_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('minimum_threshold', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('last_refill_date', sa.Date(), nullable=True),
    sa.Column('estimated_depletion_date', sa.Date(), nullable=True),
    sa.Column('recommended_refill_date', sa.Date(), nullable=True),
    sa.Column('low_stock_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_quantity >= 0', name='ck_inventory_current_quantity'),
    sa.CheckConstraint('minimum_threshold >= 0', name='ck_inventory_min_threshold'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_medication_id')
    )
    op.create_table('medication_dose_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_medication_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_taken_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snoozed_until_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dose_quantity_taken', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'TAKEN', 'MISSED', 'SNOOZED', 'SKIPPED')", name='ck_dose_event_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dose_events_med_status_time', 'medication_dose_events', ['patient_medication_id', 'status', 'scheduled_timestamp'], unique=False)
    op.create_index('idx_dose_events_patient_schedule', 'medication_dose_events', ['patient_id', 'scheduled_timestamp'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('dose_event_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('INITIAL_STOCK', 'DOSE_CONSUMPTION', 'MANUAL_REFILL', 'STOCK_ADJUSTMENT', 'DISCARDED')", name='ck_inv_tx_type'),
    sa.ForeignKeyConstraint(['dose_event_id'], ['medication_dose_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_id'], ['medicine_inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_tx_created', 'inventory_transactions', ['inventory_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_medication_id', sa.UUID(), nullable=True),
    sa.Column('dose_event_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivery_channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("delivery_channel IN ('IN_APP', 'PUSH', 'SMS', 'EMAIL')", name='ck_notification_channel'),
    sa.CheckConstraint("notification_type IN ('DOSE_REMINDER', 'MISSED_DOSE_ALERT', 'LOW_STOCK_REFILL', 'PRESCRIPTION_EXPIRY', 'CAREGIVER_ALERT')", name='ck_notification_type'),
    sa.CheckConstraint("status IN ('SCHEDULED', 'SENT', 'DELIVERED', 'FAILED', 'READ')", name='ck_notification_status'),
    sa.ForeignKeyConstraint(['dose_event_id'], ['medication_dose_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_recipient_status', 'notifications', ['recipient_user_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_notifications_scheduled_queue', 'notifications', ['status', 'scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_scheduled_queue', table_name='notifications')
    op.drop_index('idx_notifications_recipient_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_inventory_tx_created', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index('idx_dose_events_patient_schedule', table_name='medication_dose_events')
    op.drop_index('idx_dose_events_med_status_time', table_name='medication_dose_events')
    op.drop_table('medication_dose_events')
    op.drop_table('medicine_inventory')
    op.drop_index('idx_medication_schedules_med_active', table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_patient_medications_patient_id'), table_name='patient_medications')
    op.drop_index('idx_patient_medications_patient_active', table_name='patient_medications')
    op.drop_table('patient_medications')
    op.drop_table('ocr_scans')
    op.drop_table('prescriptions')
    op.drop_table('caregiver_patient_assignments')
    op.drop_table('patient_profiles')
    op.drop_table('caregiver_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_generic_name'), table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
