"""create_notifications_table

Revision ID: 67ba7715aefd
Revises: cec1af56bf41
Create Date: 2026-08-31 17:00:34.253592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67ba7715aefd'
down_revision: Union[str, Sequence[str], None] = 'cec1af56bf41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('related_dose_event_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('related_medicine_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.alter_column('notifications', 'recipient_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_notifications_recipient_status'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_scheduled_queue'), table_name='notifications')
    op.create_index('idx_notifications_patient_created', 'notifications', ['patient_id', 'created_at'], unique=False)
    op.create_index('idx_notifications_patient_unread', 'notifications', ['patient_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_patient_id'), 'notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_dose_event_id'), 'notifications', ['related_dose_event_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_medicine_id'), 'notifications', ['related_medicine_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('uq_notifications_dose_event_type', 'notifications', ['related_dose_event_id', 'type'], unique=True, postgresql_where=sa.text('related_dose_event_id IS NOT NULL'))
    op.drop_constraint(op.f('notifications_patient_medication_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_dose_event_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'medication_dose_events', ['related_dose_event_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'patient_medications', ['related_medicine_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ck_notification_channel'), 'notifications', type_='check')
    op.drop_constraint(op.f('ck_notification_status'), 'notifications', type_='check')
    op.drop_column('notifications', 'scheduled_for')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'dose_event_id')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'patient_medication_id')
    op.drop_column('notifications', 'delivery_channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('delivery_channel', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('patient_medication_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('dose_event_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('ck_notification_status'), 'notifications', "status::text = ANY (ARRAY['SCHEDULED'::character varying, 'SENT'::character varying, 'DELIVERED'::character varying, 'FAILED'::character varying, 'READ'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_notification_channel'), 'notifications', "delivery_channel::text = ANY (ARRAY['IN_APP'::character varying, 'PUSH'::character varying, 'SMS'::character varying, 'EMAIL'::character varying]::text[])")
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_dose_event_id_fkey'), 'notifications', 'medication_dose_events', ['dose_event_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('notifications_patient_medication_id_fkey'), 'notifications', 'patient_medications', ['patient_medication_id'], ['id'], ondelete='SET NULL')
    op.drop_index('uq_notifications_dose_event_type', table_name='notifications', postgresql_where=sa.text('related_dose_event_id IS NOT NULL'))
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_medicine_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_dose_event_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_patient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notifications_patient_unread', table_name='notifications')
    op.drop_index('idx_notifications_patient_created', table_name='notifications')
    op.create_index(op.f('idx_notifications_scheduled_queue'), 'notifications', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('idx_notifications_recipient_status'), 'notifications', ['recipient_user_id', 'status', 'created_at'], unique=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('notifications', 'recipient_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'related_medicine_id')
    op.drop_column('notifications', 'related_dose_event_id')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
