"""create_medication_schedule_times_and_update_schedules

Revision ID: b6b797c9f8e1
Revises: 31956e6dd748
Create Date: 2026-08-31 15:38:37.833016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6b797c9f8e1'
down_revision: Union[str, Sequence[str], None] = '31956e6dd748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_schedule_times',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('time_of_day_type', sa.String(length=20), nullable=True),
    sa.Column('dose_quantity', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("time_of_day_type IS NULL OR time_of_day_type IN ('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', 'CUSTOM')", name='ck_schedule_time_time_of_day'),
    sa.CheckConstraint('dose_quantity IS NULL OR dose_quantity > 0', name='ck_schedule_time_dose_quantity'),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_times_sched_time', 'medication_schedule_times', ['schedule_id', 'scheduled_time'], unique=False)
    op.create_index(op.f('ix_medication_schedule_times_schedule_id'), 'medication_schedule_times', ['schedule_id'], unique=False)
    op.add_column('medication_schedules', sa.Column('dosage_unit', sa.String(length=30), nullable=True))
    op.add_column('medication_schedules', sa.Column('interval_days', sa.Integer(), nullable=True))
    op.add_column('medication_schedules', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('medication_schedules', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('medication_schedules', sa.Column('instructions', sa.String(length=255), nullable=True))
    op.alter_column('medication_schedules', 'time_of_day_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('medication_schedules', 'scheduled_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.drop_constraint(op.f('ck_schedule_time_of_day'), 'medication_schedules', type_='check')
    op.create_check_constraint('ck_schedule_date_range', 'medication_schedules', 'end_date IS NULL OR end_date >= start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_schedule_date_range', 'medication_schedules', type_='check')
    op.create_check_constraint(op.f('ck_schedule_time_of_day'), 'medication_schedules', "time_of_day_type::text = ANY (ARRAY['MORNING'::character varying, 'AFTERNOON'::character varying, 'EVENING'::character varying, 'NIGHT'::character varying, 'CUSTOM'::character varying]::text[])")
    op.alter_column('medication_schedules', 'scheduled_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('medication_schedules', 'time_of_day_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('medication_schedules', 'instructions')
    op.drop_column('medication_schedules', 'end_date')
    op.drop_column('medication_schedules', 'start_date')
    op.drop_column('medication_schedules', 'interval_days')
    op.drop_column('medication_schedules', 'dosage_unit')
    op.drop_index(op.f('ix_medication_schedule_times_schedule_id'), table_name='medication_schedule_times')
    op.drop_index('idx_schedule_times_sched_time', table_name='medication_schedule_times')
    op.drop_table('medication_schedule_times')
    # ### end Alembic commands ###
