"""add_unique_constraint_to_medication_dose_events

Revision ID: cec1af56bf41
Revises: 005ef9b9bf14
Create Date: 2026-08-31 16:07:37.394036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec1af56bf41'
down_revision: Union[str, Sequence[str], None] = '005ef9b9bf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_dose_event_schedule_timestamp', 'medication_dose_events', ['schedule_id', 'scheduled_timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dose_event_schedule_timestamp', 'medication_dose_events', type_='unique')
    # ### end Alembic commands ###
