# Generated by Django 5.0.6 on 2026-09-13 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0003_medicinecatalog"),
        ("reminders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("SPECIFIC_DAYS", "Specific Days"),
                            ("INTERVAL_DAYS", "Interval Days"),
                            ("AS_NEEDED", "As Needed"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "dose_quantity",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
                ),
                ("dosage_unit", models.CharField(blank=True, max_length=30, null=True)),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("interval_days", models.PositiveIntegerField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "instructions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medications.medication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationDoseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_timestamp", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("TAKEN", "Taken"),
                            ("MISSED", "Missed"),
                            ("SNOOZED", "Snoozed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("actual_taken_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "snoozed_until_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "dose_quantity_taken",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient_medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_events",
                        to="medications.medication",
                    ),
                ),
                (
                    "recorded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_dose_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dose_events",
                        to="reminders.medicationschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MedicationScheduleTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.TimeField()),
                (
                    "time_of_day_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MORNING", "Morning"),
                            ("AFTERNOON", "Afternoon"),
                            ("EVENING", "Evening"),
                            ("NIGHT", "Night"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "dose_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_times",
                        to="reminders.medicationschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.AddIndex(
            model_name="medicationschedule",
            index=models.Index(
                fields=["medication", "is_active"], name="schedule_med_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationdoseevent",
            index=models.Index(
                fields=["patient", "scheduled_timestamp"], name="dose_patient_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationdoseevent",
            index=models.Index(
                fields=["patient_medication", "status", "scheduled_timestamp"],
                name="dose_med_status_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicationdoseevent",
            constraint=models.UniqueConstraint(
                fields=("schedule", "scheduled_timestamp"),
                name="unique_schedule_dose_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="medicationscheduletime",
            index=models.Index(
                fields=["schedule", "scheduled_time"], name="schedule_time_idx"
            ),
        ),
    ]
