# Generated by Django 5.0.6 on 2026-09-13 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_loginhistory_systemlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("medication_reminders", models.BooleanField(default=True)),
                ("missed_dose_alerts", models.BooleanField(default=True)),
                ("refill_alerts", models.BooleanField(default=True)),
                ("system_notifications", models.BooleanField(default=True)),
                ("reminder_sound", models.BooleanField(default=True)),
                ("reminder_lead_time", models.PositiveIntegerField(default=15)),
                ("language", models.CharField(default="English", max_length=30)),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12", "12-hour"), ("24", "24-hour")],
                        default="12",
                        max_length=5,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                        ],
                        default="DD/MM/YYYY",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
