# Generated by Django 5.0.6 on 2026-09-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_refill"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("dosage", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
