# Generated by Django 5.0.6 on 2026-08-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_logs",
                        to="medications.medication",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
    ]
